project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"

book:
  title: "Box: Placing module system into R"
  author:
    - name: "Joshua Marie"
    - name: "John Riz Bagnol"
  # optional: author, date, subtitle, image, etc.
  sidebar:
    title: "Box: Placing module system into R"
    style: docked
    search: true
    contents:
      - section: "Chapter 1: Introduction"
        contents:
          - index.qmd
          - 1-intro.qmd
          - 1.1-start.qmd
      - section: "Chapter 2: Loading external packages"
        contents:
          - 2-box-fundamentals.qmd
          - 2.1-imports.qmd
          - 2.2-reloading-modules.qmd
      - section: "Chapter 3: Creating Modules"
        contents:
          - 3-struct-module.qmd
          - 3.1-struct-module-1.qmd
          - 3.2-struct-module-2.qmd
          - 3.3-add-data.qmd
          - 3.4-nested-modules.qmd
          # 3.5-compiled-codes.qmd is not present in repo — add it here if/when available
      - section: "Chapter 4: Testing Modules"
        contents:
          - 4-testing-modules.qmd
          - 4.1-testthat.qmd
          - 4.2-testthat-2.qmd

  navbar:
    left:
      - href: index.qmd
        text: Home

  # explicit chapter order and numbering (index.qmd is required)
  chapters:
    - index.qmd
    - 1-intro.qmd
    - 1.1-start.qmd
    - 2-box-fundamentals.qmd
    - 2.1-imports.qmd
    - 2.2-reloading-modules.qmd
    - 3-struct-module.qmd
    - 3.1-struct-module-1.qmd
    - 3.2-struct-module-2.qmd
    - 3.3-add-data.qmd
    - 3.4-nested-modules.qmd
    # - 3.5-compiled-codes.qmd   # add when the file exists
    - 4-testing-modules.qmd
    - 4.1-testthat.qmd
    - 4.2-testthat-2.qmd

  repo-url: https://github.com/kisha126/box-r  # replace with your actual repo
  repo-actions: [edit, issue]  # makes pages editable and links to open issues

format:
  html:
    theme:
      light: [default, custom-light.scss]
      dark: [darkly, custom-dark.scss]
    css: styles.css
    toc: true
    number-sections: false
    code-copy: true
    page-navigation: true

execute:
  warning: false
  message: false
  # freeze: auto
